---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: directory
  path: src/content/posts
  label: Blog Posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: src/content/images
  label: Images
  create: documents
  match: "**/*"
  templates:
  - latest-images
upload_dir: ''
public_path: https://res.cloudinary.com/dhat0b0ey/image/upload
front_matter_path: https://res.cloudinary.com/dhat0b0ey/image/upload/v1588167873/portfolio/latestimages
use_front_matter_path: false
file_template: 'portfolio/latestimages/:filename:'
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
